# Generated by Django 2.1.2 on 2018-11-08 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0002_auto_20181108_0311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_end_product',
        ),
    ]
