# Generated by Django 2.1.2 on 2018-12-09 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0005_auto_20181206_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='biddingtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
