# Generated by Django 2.1.2 on 2018-12-09 20:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0006_bidding_biddingtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidding',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='bidding',
            name='openuntil',
        ),
        migrations.AddField(
            model_name='clothes',
            name='openuntil',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
