# Generated by Django 2.1.2 on 2018-12-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0007_auto_20181209_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='latestprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
