# Generated by Django 2.1.2 on 2018-12-09 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0008_clothes_latestprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='latestprice',
        ),
    ]
