# Generated by Django 2.1.2 on 2018-12-11 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0009_remove_clothes_latestprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='numtrade',
        ),
    ]
